//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Lenders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub lender_id: i32,
    pub lender_name: String,
    #[sea_orm(unique)]
    pub lender_email: String,
    #[sea_orm(unique)]
    pub lender_password: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::loan_products::Entity")]
    LoanProducts,
}

impl Related<super::loan_products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanProducts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
