//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub mod prelude;

pub mod borrower_payment_ledger;
pub mod borrowers;
pub mod lender_loan_product_ledger;
pub mod lenders;
pub mod loan_products;
pub mod loan_requests;
pub mod loan_transactions;
pub mod payment_details;
pub mod payments;
pub mod sea_orm_active_enums;
