//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::borrower_payment_ledger::Entity as BorrowerPaymentLedger;
pub use super::borrowers::Entity as Borrowers;
pub use super::lender_loan_product_ledger::Entity as LenderLoanProductLedger;
pub use super::lenders::Entity as Lenders;
pub use super::loan_products::Entity as LoanProducts;
pub use super::loan_requests::Entity as LoanRequests;
pub use super::loan_transactions::Entity as LoanTransactions;
pub use super::payment_details::Entity as PaymentDetails;
pub use super::payments::Entity as Payments;
